Dm 217 fetch publizon record from ticklerepo
DBCDK/dataio pull request #51
Opened 2022-05-05 11:31 UTC by jesper-bruun

2022-05-05 13:26 UTC, MichelLyck commented on harvester/dmat/src/main/java/dk/dbc/dataio/harvester/dmat/TickleFetcher.java
> +                    JobSpecificationTemplate.SUBMITTER_NUMBER_PUBLIZON));
Er dataSetName uinteressant i denne sammenhæng ?

2022-05-05 13:41 UTC, MichelLyck commented on harvester/dmat/src/test/resources/META-INF/persistence.xml
> +  ~ Copyright (C) 2015 Dansk Bibliotekscenter a/s, Tempovej 7-11, DK-2750 Ballerup,
Det her copyright hejs skal vel væk

2022-05-05 13:42 UTC, MichelLyck approved these changes

2022-05-06 09:05 UTC, hwhadbc requested changes

2022-05-06 09:05 UTC, hwhadbc commented on harvester/dmat/src/test/java/dk/dbc/dataio/harvester/dmat/HarvestOperationTest.java
> +            verify(flowStoreServiceConnector).updateHarvesterConfig(any(DMatHarvesterConfig.class));});
Mangler det ikke et check for om posten er høstet fra kilderepo ?

2022-05-11 08:23 UTC, hwhadbc approved these changes

2022-05-11 10:44 UTC, merged